# Generated by Django 4.2.5 on 2023-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('password1', models.CharField(max_length=50)),
            ],
        ),
    ]
