# Generated by Django 4.2.5 on 2023-10-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email1',
            new_name='fullemail1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='fullmessage',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fullname',
        ),
    ]
